CREATE TABLE COUNTERPARTIES (
    CPRT_ID           BIGINT NOT NULL,
    CPRT_NAME_TX      VARCHAR(50) NOT NULL,
    CPRT_SHRT_NAME_TX VARCHAR(30),
    CPRT_NIP_TX       VARCHAR(10),
    CPRT_ACCO_NUMB_TX VARCHAR(26),
    ADDR_STRE_TX      VARCHAR(50),
    ADDR_POST_TX      VARCHAR(10),
    ADDR_CITY_TX      VARCHAR(30),
    ADDR_CNTR_TX      VARCHAR(50),
    CREA_DT           TIMESTAMP,
    UPDT_DT           TIMESTAMP,
    VERS_NM           INTEGER
);

CREATE UNIQUE INDEX COUNTERPARTIES_PK ON COUNTERPARTIES(CPRT_ID);
ALTER TABLE COUNTERPARTIES ADD CONSTRAINT COUNTERPARTIES_PK PRIMARY KEY(CPRT_ID);